// Auto-generated from settings.py
// NOTE: Manual review required for runtime parity.

// TODO(import): import os

// TODO(import): import pyxel

let EDITOR_IMAGE_FILE = "assets/editor_220x160.png";
let EDITOR_IMAGE = pyxel.Image.from_image(;
    os.path.join(os.path.dirname(__file__), EDITOR_IMAGE_FILE);
// TODO(python): )

let APP_WIDTH = 240;
let APP_HEIGHT = 180;

let TOOL_SELECT = 0;
let TOOL_PENCIL = 1;
let TOOL_RECTB = 2;
let TOOL_RECT = 3;
let TOOL_CIRCB = 4;
let TOOL_CIRC = 5;
let TOOL_BUCKET = 6;

let MAX_SOUND_LENGTH = 48;
let MAX_MUSIC_LENGTH = 32;

let TEXT_LABEL_COLOR = 7;
let HELP_MESSAGE_COLOR = 5;

let PANEL_FOCUS_COLOR = 7;
let PANEL_FOCUS_BORDER_COLOR = 0;
let PANEL_SELECT_FRAME_COLOR = 15;
let PANEL_SELECT_BORDER_COLOR = 0;

let PIANO_KEYBOARD_REST_COLOR = 12;
let PIANO_KEYBOARD_PLAY_COLOR = 14;

let PIANO_ROLL_CURSOR_PLAY_COLOR = 14;
let PIANO_ROLL_CURSOR_EDIT_COLOR = 6;
let PIANO_ROLL_CURSOR_SELECT_COLOR = 15;
let PIANO_ROLL_BACKGROUND_COLOR = 7;
let PIANO_ROLL_NOTE_COLOR = 8;
let PIANO_ROLL_REST_COLOR = 5;

let OCTAVE_BAR_BACKGROUND_COLOR = 7;
let OCTAVE_BAR_COLOR = 13;

let SOUND_FIELD_DATA_NORMAL_COLOR = 1;
let SOUND_FIELD_DATA_SELECT_COLOR = 7;
let SOUND_FIELD_CURSOR_EDIT_COLOR = 1;
let SOUND_FIELD_CURSOR_SELECT_COLOR = 2;

let MUSIC_FIELD_BACKGROUND_COLOR = 6;
let MUSIC_FIELD_SOUND_NORMAL_COLOR = 1;
let MUSIC_FIELD_SOUND_SELECT_COLOR = 7;
let MUSIC_FIELD_CURSOR_PLAY_COLOR = 8;
let MUSIC_FIELD_CURSOR_EDIT_COLOR = 1;
let MUSIC_FIELD_CURSOR_SELECT_COLOR = 2;
